static void (*rule_action[]) (void) = {NULL,
     null_action, /* 1 */
     null_action, /* 2 */
     bad_first_symbol, /* 3 */
     bad_first_symbol, /* 4 */
     bad_first_symbol, /* 5 */
     bad_first_symbol, /* 6 */
     bad_first_symbol, /* 7 */
     bad_first_symbol, /* 8 */
     bad_first_symbol, /* 9 */
     act10, /* 10 */
     null_action, /* 11 */
     null_action, /* 12 */
     act13, /* 13 */
     act14, /* 14 */
     null_action, /* 15 */
     act16, /* 16 */
     bad_macro_name, /* 17 */
     bad_macro_name, /* 18 */
     bad_macro_name, /* 19 */
     bad_macro_name, /* 20 */
     act21, /* 21 */
     act22, /* 22 */
     null_action, /* 23 */
     definition_expected, /* 24 */
     definition_expected, /* 25 */
     definition_expected, /* 26 */
     definition_expected, /* 27 */
     definition_expected, /* 28 */
     definition_expected, /* 29 */
     definition_expected, /* 30 */
     null_action, /* 31 */
     null_action, /* 32 */
     null_action, /* 33 */
     process_terminals_prolog, /* 34 */
     process_terminal, /* 35 */
     process_terminal, /* 36 */
     process_terminal, /* 37 */
     bad_terminal, /* 38 */
     bad_terminal, /* 39 */
     null_action, /* 40 */
     act41, /* 41 */
     null_action, /* 42 */
     null_action, /* 43 */
     null_action, /* 44 */
     null_action, /* 45 */
     null_action, /* 46 */
     null_action, /* 47 */
     null_action, /* 48 */
     null_action, /* 49 */
     null_action, /* 50 */
     null_action, /* 51 */
     null_action, /* 52 */
     null_action, /* 53 */
     null_action, /* 54 */
     null_action, /* 55 */
     bad_alias_rhs, /* 56 */
     bad_alias_rhs, /* 57 */
     bad_alias_rhs, /* 58 */
     act59, /* 59 */
     null_action, /* 60 */
     act61, /* 61 */
     missing_quote, /* 62 */
     missing_quote, /* 63 */
     null_action, /* 64 */
     act65, /* 65 */
     bad_start_symbol, /* 66 */
     bad_start_symbol, /* 67 */
     bad_start_symbol, /* 68 */
     bad_start_symbol, /* 69 */
     act70, /* 70 */
     misplaced_keyword_found_in_START_section, /* 71 */
     misplaced_keyword_found_in_START_section, /* 72 */
     misplaced_keyword_found_in_START_section, /* 73 */
     misplaced_keyword_found_in_START_section, /* 74 */
     act75, /* 75 */
     act76, /* 76 */
     null_action, /* 77 */
     null_action, /* 78 */
     act79, /* 79 */
     act80, /* 80 */
     act81, /* 81 */
     null_action, /* 82 */
     null_action, /* 83 */
     act84, /* 84 */
     act85, /* 85 */
     bad_first_symbol_in_RULES_section, /* 86 */
     bad_first_symbol_in_RULES_section, /* 87 */
     bad_first_symbol_in_RULES_section, /* 88 */
     bad_first_symbol_in_RULES_section, /* 89 */
     rule_without_left_hand_side, /* 90 */
     rule_without_left_hand_side, /* 91 */
     rule_without_left_hand_side, /* 92 */
     act93, /* 93 */
     act94, /* 94 */
     act95, /* 95 */
     misplaced_keyword_found_in_RULES_section, /* 96 */
     misplaced_keyword_found_in_RULES_section, /* 97 */
     misplaced_keyword_found_in_RULES_section, /* 98 */
     misplaced_keyword_found_in_RULES_section, /* 99 */
     misplaced_keyword_found_in_RULES_section, /* 100 */
     null_action, /* 101 */
     act102, /* 102 */
     null_action, /* 103 */
     null_action, /* 104 */
     null_action, /* 105 */
     null_action, /* 106 */
     null_action, /* 107 */
     null_action, /* 108 */
     null_action, /* 109 */
     null_action, /* 110 */
     null_action, /* 111 */
     misplaced_keyword_found_in_NAMES_section, /* 112 */
     misplaced_keyword_found_in_NAMES_section, /* 113 */
     misplaced_keyword_found_in_NAMES_section, /* 114 */
     misplaced_keyword_found_in_NAMES_section, /* 115 */
     misplaced_keyword_found_in_NAMES_section, /* 116 */
     misplaced_keyword_found_in_NAMES_section, /* 117 */
     act118, /* 118 */
     act119, /* 119 */
     null_action, /* 120 */
     null_action, /* 121 */
     process_TERMINALS_section, /* 122 */
     process_TERMINALS_section, /* 123 */
     process_ALIAS_section, /* 124 */
     process_ALIAS_section, /* 125 */
     null_action, /* 126 */
     null_action, /* 127 */
     null_action, /* 128 */
     null_action, /* 129 */
     null_action, /* 130 */
     null_action, /* 131 */
     null_action, /* 132 */
     null_action, /* 133 */
     act134, /* 134 */
     null_action, /* 135 */
     null_action, /* 136 */
     null_action, /* 137 */
     null_action, /* 138 */
     null_action, /* 139 */
     null_action, /* 140 */
     null_action, /* 141 */
     null_action, /* 142 */
     null_action, /* 143 */
     NULL};
